name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Gerar a cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#6D28D9&color_dots=#EBEDF0,#DDD6FE,#C4B5FD,#A78BFA,#7C3AED
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#A855F7&color_dots=#161B22,#4C1D95,#6D28D9,#8B5CF6,#C4B5FD

      - name: Publicar na branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
